### ISSUE TITLE
Running `NuGet.exe pack` in parallel causes System.ObjectDisposedException (Can not access a closed Stream)

### ISSUE THREAD

**Issue by zentron** [NuGet/NuGet.CommandLine#18]
Running the following pack script against several different packages (note completely different source and destination)

```
 cls
 
  $ScriptBlock = {
    param($ver) 
    Write-Host "[processing Package # '$ver' inside the job]"
    & "C:\Temp\NuGet.exe" pack "D:\Development\Packages\Acme.Web$ver\Acme.Web.nuspec" -NoPackageAnalysis -BasePath "D:\Development\Packages\Acme.Web$ver" -OutputDirectory "C:\Temp" -Version 1.0.$ver -Verbosity Detailed 
  }

#Run 3 Jobs
  for($i=1; $i -le 3; $i++) {
    Start-Job $ScriptBlock -ArgumentList $i
  }

 # Wait for all to complete
While (Get-Job -State "Running") { Start-Sleep 2 }

# Display output from all jobs
Get-Job | Receive-Job

Remove-Job *
```

Results in 2/3 failing with 
```
System.ObjectDisposedException: Can not access a closed Stream.
    + CategoryInfo          : NotSpecified: (System.ObjectDi... closed Stream.:String) [], Remote 
   Exception
    + FullyQualifiedErrorId : NativeCommandError
    + PSComputerName        : localhost
 
   at System.IO.Compression.DeflateStream.EnsureNotDisposed()
   at System.IO.Compression.DeflateStream.Flush()
   at MS.Internal.IO.Packaging.CompressStream.Flush()
   at MS.Internal.IO.Z
ip.ProgressiveCrcCalculatingStream.Flush()
   at MS.Internal.IO.Zip.ZipIOLocalFileBlock.FlushExposedStreams()
   at MS.Internal.IO.Zip.ZipIOLocalFileBlock.UpdateReferences(Boolean closingFlag)
   at MS.Internal.IO.Zip.ZipIOBlockManager.SaveContainer(Boolean closingFlag)
   at MS.Internal.IO.Zip.ZipIOBlockManager.SaveStream(ZipIOLocalFileBlock blockRequestingFlush, 
Boolean closingFlag)
   at MS.Internal.IO.Zip.ZipIOModeEnforcingStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.Packaging.PackagePart.Close()
   at System.IO.Packaging.Package.DoClose(PackagePart p)
   at System.IO.Packaging.Package.DoOperationOnEachPart(PartOperation operation)
   at System.IO.Packaging.Package.System.IDisposable.Dispose()
   at NuGet.PackageBuilder.Save(Stream stream)
   at NuGet.Commands.PackCommand.BuildPackage(PackageBuilder builder, String outputPath)
   at NuGet.Commands.PackCommand.BuildFromNuspec(String path)
   at NuGet.Commands.PackCommand.BuildPackage(String path)
   at NuGet.Commands.PackCommand.ExecuteCommand()
   at NuGet.Commands.Command.Execute()
   at NuGet.Program.Main(String[] args)
```

Not sure if there is some limitation or argument not being supplied to get this process to work.

**Comment by deepakaravindr** [comment]
Filed https://github.com/NuGet/Home/issues/1282 to track this issue.

For filing new bugs on exe, please use https://github.com/NuGet/Home/issues

Please check out the new https://github.com/NuGet/NuGet.CommandLine/blob/master/README.md. The NuGet Command line (nuget.exe) is now building at the nuget.packagemanagement repo.

The latest nuget.exe that is public today can be found at http://dist.nuget.org/win-x86-commandline/v3.1.0-beta/nuget.exe. We have another release of nuget.exe coming up soon
